---
- hosts: all
  gather_facts: true
  vars: 
    prometheus_version: "2.45.0"
    grafana_version: "10.0.3-1"
  # roles:
  #   - prometheus
  #   - grafana
  pre_tasks:
    - name: Wait for SSH port to be open
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        delay: 15
        timeout: 300
    - name: Print host info
      debug:
       var: ansible_host
  # post_tasks:
  #   - systemd:
  #       daemon_reexec: true
  #     become: true